name: Docker Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: hello-action
        uses: ./.github/actions/hello-world
        with: 
          firstGreating: "Richard Saavedra"
          secondGreeting: "Angela Hoyos"
          thirdGreating: "Mateo Saavedra"
